### ISSUE TITLE
undefined method `release_relationship' for #<Issue:0xaf465a0> when upgrading to v1.0.0

### ISSUE THREAD

**Issue by pibako** [backlogs/redmine_backlogs#915]
platform:  # supported: 2.2.4, 2.3.0
backlogs:  # supported: 1.0.0
ruby:  # supported: 1.9.3, 2.0.0

Hi,

I'm trying migrate backlogs:
- current: v0.9.35
- target: v1.0.0

Redmine 2.2.4
Ruby 1.9.3p392

I'm getting the following error which I think might be related to #908. 

```
root@zweb4:/var/web/redmine# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
Migrating redmine_backlogs (Redmine Backlogs)...
==  MigrateReleases: migrating ================================================
-- add_column(:releases, :status, :string, {:null=>false, :default=>"open"})
   -> 0.0620s
-- add_column(:releases, :description, :text)
   -> 0.0006s
Migrating implicit releases...
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `release_relationship' for #<Issue:0xaf465a0>
/var/web/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:313:in `block (3 levels) in integrate_implicit_stories'
/var/web/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:309:in `block (2 levels) in integrate_implicit_stories'
/var/web/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:306:in `each'
/var/web/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:306:in `block in integrate_implicit_stories'
/var/web/redmine/plugins/redmine_backlogs/app/models/rb_release.rb:301:in `integrate_implicit_stories'
/var/web/redmine/plugins/redmine_backlogs/db/migrate/042_migrate_releases.rb:7:in `up'
/var/web/redmine/lib/redmine/plugin.rb:449:in `migrate_plugin'
/var/web/redmine/lib/redmine/plugin.rb:421:in `migrate'
/var/web/redmine/lib/redmine/plugin.rb:435:in `block in migrate'
/var/web/redmine/lib/redmine/plugin.rb:434:in `each'
/var/web/redmine/lib/redmine/plugin.rb:434:in `migrate'
/var/web/redmine/lib/tasks/redmine.rake:69:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```
