### ISSUE TITLE
Adding support to 3.0.1?

### ISSUE THREAD

**Issue by rlisowski** [backlogs/redmine_backlogs#1097]
Any plans for 3.0.1 support?

**Comment by suexID** [comment]
That would be greatly appreciated! :)

**Comment by phoebusnetto** [comment]
Hope they support. I'm changing my Project Management Tools to Redmine and Backlogs is one of the most valuable plugin I found for development!

**Comment by korin** [comment]
@phoebusnetto this repo seems dead (last commit 9 months ago), but you can ask on forum http://forum.redminebacklogs.net/

**Comment by forgulencia** [comment]
Please!

**Comment by cecconel** [comment]
+1

**Comment by PierreF66** [comment]
+1

**Comment by korin** [comment]
Here is my version compatible with redmine 3.x https://github.com/efigence/redmine_backlogs/tree/feature/3.0
If you wanna use it, be careful there are still dragons :) and I'm using [redmine_sidekiq](https://github.com/ogom/redmine_sidekiq)

**Comment by AlexDAlexeev** [comment]
@korin God job! You saved my time!
I made fork of your redmine_backlogs and removed sidekiq to work on windows.
https://github.com/AlexDAlexeev/redmine_backlogs
There still some problems, but it works for me with Redmine 3.0.1

**Comment by korin** [comment]
Yes, there are many warnings. I think I will switch to Active Job so anyone could use any background processing tool.

**Comment by ali-sattari** [comment]
+1

**Comment by joshuacox** [comment]
+1 tested with 3.0.3

**Comment by patrickatamaniuk** [comment]
i'm looking into it.

**Comment by patrickatamaniuk** [comment]
check the branch feature/redmine3 it now passes all travis tests and should work.

**Comment by jdpf** [comment]
I am trying feature/redmine3 now, but the rake install task fails claiming that I have two instances of psych. Even when moving redmine_backlogs out of the plugins directory, it still fails with:

```
$ bundle exec rake redmine:backlogs:install
/usr/lib/x86_64-linux-gnu/ruby/2.1.0/psych.so: warning: already initialized constant Psych::Parser::ANY
/usr/lib/x86_64-linux-gnu/ruby/2.1.0/psych.so: warning: already initialized constant Psych::Parser::UTF8

SNIP

/opt/redmine/redmine/config/application.rb:5:in `<top (required)>'
/opt/redmine/redmine/Rakefile:5:in `require'
/opt/redmine/redmine/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
````

While it is unclear to me if this is indeed error in my installed gems, the rake install task for redmine_backlogs reliably exercises the issue. So I am, perhaps prematurely, asking for help. 

The redmine installation and associated plugins appears to be working otherwise with redmine_backlogs removed from the plugin directory.

Here is the output of gem list (truncated to only show psych). 

```
psych (2.0.13, 2.0.5)
```

Any hints? 

Thanks!

**Comment by Jellyfrog** [comment]
Works fine for me, only used it for a week tho. Maybe it's time to merge and make a new release?

**Comment by Kakakakakku** [comment]
+1

**Comment by jdpf** [comment]
DoH!

Apparently, my issue here is that I forgot to append ```RAILS_ENV=production``` to the install task invocation. 

```$ bundle exec rake redmine:backlogs:install``` fails, but 
```$ bundle exec rake redmine:backlogs:install RAILS_ENV=production``` succeeds!

It works! YAY!

```
redmine$ bundle exec rake redmine:backlogs:install RAILS_ENV=production
3.1.0.stable. You are running backlogs v1.0.6, latest version is 1.0.6

=====================================================
             Redmine Backlogs Installer
=====================================================
Installing to the production environment.
Fetching card labels from http://git.gnome.org...done!
Story and task trackers are now set.
Migrating the database...done!
Installation complete. Please restart Redmine.
Thank you for trying out Redmine Backlogs!
```

Thank You!

**Comment by intZero** [comment]
Hi, I'm trying to get backlogs to work on the latest Bitnami Redmine (3.1.1) . I've switched branches to feature/redmine3 and it installed with no probs on a clean database. Unfortunately, after I followed these instructions: https://wiki.bitnami.com/Applications/BitNami_Redmine#Backup
To upgrade the old database to the new format...

The plugin migration gets upset:
```
D:\Bitnami\redmine-3.1.1-0\apps\redmine\htdocs>ruby bin/rake redmine:plugins RAI
LS_ENV="production"
DL is deprecated, please use Fiddle
Migrating redmine_backlogs (Redmine Backlogs)...
== 38 RbAddHistory: migrating =================================================
Rebuilding history...
    37 (     1/1060)...
    38 (     2/1060)...
    39 (     3/1060)...
    41 (     4/1060)...
    42 (     5/1060)...
    45 (     6/1060)...
    46 (     7/1060)...
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `id' for 1:FixnumD:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs
/plugins/redmine_backlogs/app/models/rb_issue_history.rb:35:in `block in statuse
s'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:150:in `yield'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:150:in `block (3 levels) in rebuild_issue'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:149:in `each'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:149:in `each_with_index'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:149:in `block (2 levels) in rebuild_issue'
D:in `each'
D:in `each'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:133:in `block in rebuild_issue'
D:in `each'
D:in `each'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:129:in `rebuild_issue'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:329:in `block in rebuild'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/app/mode
ls/rb_issue_history.rb:327:in `rebuild'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/plugins/redmine_backlogs/db/migra
te/038_rb_add_history.rb:35:in `up'
D:in `migrate'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:481:in `mig
rate_plugin'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:453:in `mig
rate'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:467:in `blo
ck in migrate'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:466:in `eac
h'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/redmine/plugin.rb:466:in `mig
rate'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/tasks/redmine.rake:127:in `bl
ock (3 levels) in <top (required)>'
D:/Bitnami/redmine-3.1.1-0/apps/redmine/htdocs/lib/tasks/redmine.rake:52:in `blo
ck (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

Any ideas what to do?

**Comment by craigcarnell** [comment]
I get:

bundle exec rake redmine:backlogs:install RAILS_ENV=production
rake aborted!
LoadError: No such file to load -- prawn

I tried sudo gem install prawn and installed 2.1.0

**Comment by wgtgithub** [comment]
HI, I have a question.
How to convert Backlog data to Redline Backlogs data?
I should do that.
