### ISSUE TITLE
Cannot create new task (Internal server error on taskboard.js)

### ISSUE THREAD

**Issue by siegerv** [backlogs/redmine_backlogs#198]
After upgrading to v0.6.8 is can no longer create a new task on the taskboard. It will not save.

Saving a task gives a javascript error: RB.urlfor is not a function (task.js line 54)

This seems to be caused by a 500 Internal server error for loading taskboard.js
This is in the log file:

Processing RbTaskboardsController#show (for 10.56.23.57 at 2011-08-26 17:24:12) [GET]
  Parameters: {"sprint_id"=>"98", "action"=>"show", "controller"=>"rb_taskboards"}
Rendering template within layouts/rb
Rendering rb_taskboards/show
Completed in 2016ms (View: 1844, DB: 156) | 200 OK [http://10.32.231.110/redmine/rb/taskboards/98]

Processing RbServerVariablesController#show to js (for 10.56.23.57 at 2011-08-26 17:24:14) [GET]
  Parameters: {"section"=>"taskboard", "sprint_id"=>"98", "format"=>"js", "project_id"=>"tridion-2010", "action"=>"show", "controller"=>"rb_server_variables"}
Rendering rb_server_variables/show

ActionView::TemplateError (undefined local variable or method `tracker' for #ActionView::Base:0x5e9a268) on line #51 of vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:
48:         catch (:done) do
49:           [[false, false], [true, true], [false, true], [true, false]].each{|creator, assignee|
50:             Tracker.find(RbTask.tracker).issue_statuses.each {|status|
51:               status.new_statuses_allowed_to(roles, tracker, creator, assignee).each{|s|
52:                 transitions = true
53:                 throw :done
54:               }

```
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:51
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:50:in `each'
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:50
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:49:in `each'
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:49
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:48:in `catch'
vendor/plugins/redmine_backlogs/app/views/rb_server_variables/show.js.erb:48
vendor/plugins/redmine_backlogs/app/controllers/rb_server_variables_controller.rb:7:in `show'
vendor/plugins/redmine_backlogs/app/controllers/rb_server_variables_controller.rb:6:in `show'
config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'
```

Rendering D:/RedmineAppl/apps/redmine/public/500.html (500 Internal Server Error)
