### ISSUE TITLE
[release graph] Problem with batch_update_attributes

### ISSUE THREAD

**Issue by bohansen** [backlogs/redmine_backlogs#540]
After merging latest master into release graph branch I get the following error when editing a release:
´´´´
NoMethodError (undefined method `batch_update_attributes' for #<RbRelease:0xb60b6d80>):
  vendor/plugins/redmine_backlogs/app/controllers/rb_releases_controller.rb:35:in`edit'
  thin (1.3.1) lib/thin/connection.rb:80:in `pre_process'
  thin (1.3.1) lib/thin/connection.rb:78:in`catch'
  thin (1.3.1) lib/thin/connection.rb:78:in `pre_process'
  thin (1.3.1) lib/thin/connection.rb:53:in`process'
  thin (1.3.1) lib/thin/connection.rb:38:in `receive_data'
´´´´
Is this supposed to work for the release class also?

Thanks in advance,
Bo
