### ISSUE TITLE
Migraiton error for v0.9.28 ("undefined method `include?' for nil:NilClass")

### ISSUE THREAD

**Issue by guikubivan** [backlogs/redmine_backlogs#757]
Edit: I'm running Redmine 1.4.4 because my Update Manager on Debian suggested I update... so I guess you can close the ticket. Will the plugin be updated to work with Redemine 1.4.4?

I'm trying to update my redmine backlogs plugin, but I get an error when I run (output below):
RAILS_ENV=production bundle exec rake redmine:backlogs:install

[.....]
Story and task trackers are now set.
Migrating the database.../usr/lib/ruby/vendor_ruby/bundler/runtime.rb:197: warning: Insecure world writable dir /media/ext4_bin/android-sdk-linux/platform-tools in PATH, mode 040777
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /usr/share/redmine/vendor/rails/railties/lib/rails/gem_dependency.rb:21.
*\* Invoke db:migrate:plugins (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute db:migrate:plugins
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `include?' for nil:NilClass
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_sprint_burndown.rb:25:in`touch!'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:269:in `touch_sprint'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:178:in`evaluate_method'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:93:in`block in run'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in `each'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:92:in`run'
/usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:276:in `run_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:344:in`callback'
/usr/lib/ruby/vendor_ruby/active_record/callbacks.rb:251:in `create_or_update_with_callbacks'
/usr/lib/ruby/vendor_ruby/active_record/base.rb:2577:in`save'
/usr/lib/ruby/vendor_ruby/active_record/validations.rb:1089:in `save_with_validation'
/usr/lib/ruby/vendor_ruby/active_record/dirty.rb:79:in`save_with_dirty'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:229:in `block in with_transaction_returning_status'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/database_statements.rb:136:in`transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:182:in `transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:228:in`with_transaction_returning_status'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:196:in `block in save_with_transactions'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:208:in`rollback_active_record_state!'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:196:in `save_with_transactions'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:212:in`rebuild_issue'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:230:in `block in rebuild'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:228:in`each'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:228:in `each_with_index'
/usr/share/redmine/vendor/plugins/redmine_backlogs/app/models/rb_issue_history.rb:228:in`rebuild'
/usr/share/redmine/vendor/plugins/redmine_backlogs/db/migrate/038_rb_add_history.rb:27:in `up'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:282:in`block in migrate'
/usr/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:282:in`migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:365:in `migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:491:in`block (2 levels) in migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:565:in `call'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:565:in`block in ddl_transaction'
/usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/usr/lib/ruby/vendor_ruby/active_record/transactions.rb:182:in`transaction'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:565:in `ddl_transaction'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:490:in`block in migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:477:in `each'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:477:in`migrate'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:401:in `up'
/usr/lib/ruby/vendor_ruby/active_record/migration.rb:383:in`migrate'
/usr/share/redmine/vendor/plugins/engines/lib/engines/plugin/migrator.rb:20:in `migrate_plugin'
/usr/share/redmine/vendor/plugins/engines/lib/engines/plugin.rb:93:in`migrate'
/usr/share/redmine/vendor/plugins/engines/lib/tasks/engines.rake:43:in `block (4 levels) in <top (required)>'
/usr/share/redmine/vendor/plugins/engines/lib/tasks/engines.rake:39:in`each'
/usr/share/redmine/vendor/plugins/engines/lib/tasks/engines.rake:39:in `block (3 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:228:in`call'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:223:in`each'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:166:in`block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:159:in`invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:143:in`invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in`each'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:110:in`run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:73:in`block in run'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.0.3/lib/rake/application.rb:70:in`run'
/var/lib/gems/1.9.1/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in`load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate:plugins
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:197: warning: Insecure world writable dir /media/ext4_bin/android-sdk-linux/platform-tools in PATH, mode 040777
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /usr/share/redmine/vendor/rails/railties/lib/rails/gem_dependency.rb:21.
*\* Invoke redmine:backlogs:fix_positions (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:backlogs:fix_positions
done!
Installation complete. Please restart Redmine.
